=== VijayEluri/tuscany-sca-1.x/das/rdb/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:org.apache.tuscany.das.rdb.config="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" ecore:nsPrefix="org.apache.tuscany.das.rdb.config" ecore:package="org.apache.tuscany.das.rdb.config" targetNamespace="http:///org.apache.tuscany.das.rdb/config.xsd">
   <xsd:import namespace="http://www.eclipse.org/emf/2002/Ecore" schemaLocation="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.xsd"/>
   <xsd:element ecore:ignore="true" name="Config" type="org.apache.tuscany.das.rdb.config:Config"/>
   <xsd:element ecore:ignore="true" name="Command" type="org.apache.tuscany.das.rdb.config:Command"/>
   <xsd:element ecore:ignore="true" name="ConnectionProperties" type="org.apache.tuscany.das.rdb.config:ConnectionProperties"/>
   <xsd:element ecore:ignore="true" name="Parameter" type="org.apache.tuscany.das.rdb.config:Parameter"/>
   <xsd:element ecore:ignore="true" name="Relationship" type="org.apache.tuscany.das.rdb.config:Relationship"/>
   <xsd:element ecore:ignore="true" name="Table" type="org.apache.tuscany.das.rdb.config:Table"/>
   <xsd:element ecore:ignore="true" name="KeyPair" type="org.apache.tuscany.das.rdb.config:KeyPair"/>
   <xsd:element ecore:ignore="true" name="Column" type="org.apache.tuscany.das.rdb.config:Column"/>
   <xsd:element ecore:ignore="true" name="ResultDescriptor" type="org.apache.tuscany.das.rdb.config:ResultDescriptor"/>
   <xsd:complexType name="Config">
      <xsd:sequence>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Command" type="org.apache.tuscany.das.rdb.config:Command"/>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" minOccurs="0" name="ConnectionProperties" type="org.apache.tuscany.das.rdb.config:ConnectionProperties"/>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Table" type="org.apache.tuscany.das.rdb.config:Table"/>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Relationship" type="org.apache.tuscany.das.rdb.config:Relationship"/>
      </xsd:sequence>
      <xsd:attribute name="uri" type="xsd:string"/>
   </xsd:complexType>
   <xsd:complexType name="Command">
      <xsd:sequence>
         <xsd:element ecore:opposite="Command" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Parameter" type="org.apache.tuscany.das.rdb.config:Parameter"/>
         <xsd:element ecore:opposite="Command" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="ResultDescriptor" type="org.apache.tuscany.das.rdb.config:ResultDescriptor"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="SQL" type="xsd:string"/>
      <xsd:attribute name="kind" type="xsd:string"/>
      <xsd:attribute ecore:opposite="Command" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="ConnectionProperties">
      <xsd:attribute name="dataSource" type="xsd:string"/>
      <xsd:attribute name="driverClassName" type="xsd:string"/>
      <xsd:attribute name="driverURL" type="xsd:string"/>
      <xsd:attribute name="driverPassword" type="xsd:string"/>
      <xsd:attribute name="driverUserName" type="xsd:string"/>
      <xsd:attribute ecore:opposite="ConnectionProperties" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Parameter">
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="columnType" type="xsd:string"/>
      <xsd:attribute ecore:opposite="Parameter" ecore:reference="org.apache.tuscany.das.rdb.config:Command" ecore:transient="true" name="Command" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Relationship">
      <xsd:sequence>
         <xsd:element ecore:opposite="Relationship" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="KeyPair" type="org.apache.tuscany.das.rdb.config:KeyPair"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="primaryKeyTable" type="xsd:string"/>
      <xsd:attribute name="foreignKeyTable" type="xsd:string"/>
      <xsd:attribute name="many" type="xsd:boolean"/>
      <xsd:attribute ecore:opposite="Relationship" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Table">
      <xsd:sequence>
         <xsd:element ecore:opposite="Table" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Column" type="org.apache.tuscany.das.rdb.config:Column"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="propertyName" type="xsd:string"/>
      <xsd:attribute name="create" type="xsd:string"/>
      <xsd:attribute name="update" type="xsd:string"/>
      <xsd:attribute name="delete" type="xsd:string"/>
      <xsd:attribute ecore:opposite="Table" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="KeyPair">
      <xsd:attribute name="primaryKeyColumn" type="xsd:string"/>
      <xsd:attribute name="foreignKeyColumn" type="xsd:string"/>
      <xsd:attribute ecore:opposite="KeyPair" ecore:reference="org.apache.tuscany.das.rdb.config:Relationship" ecore:transient="true" name="Relationship" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Column">
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="propertyName" type="xsd:string"/>
      <xsd:attribute name="converterClassName" type="xsd:string"/>
      <xsd:attribute name="columnType" type="xsd:string"/>
      <xsd:attribute name="primaryKey" type="xsd:boolean"/>
      <xsd:attribute name="generated" type="xsd:boolean"/>
      <xsd:attribute name="collision" type="xsd:boolean"/>
      <xsd:attribute ecore:opposite="Column" ecore:reference="org.apache.tuscany.das.rdb.config:Table" ecore:transient="true" name="Table" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="ResultDescriptor">
      <xsd:attribute name="columnName" type="xsd:string"/>
      <xsd:attribute name="tableName" type="xsd:string"/>
      <xsd:attribute name="columnType" type="xsd:string"/>
      <xsd:attribute name="converter" type="xsd:string"/>
      <xsd:attribute ecore:opposite="ResultDescriptor" ecore:reference="org.apache.tuscany.das.rdb.config:Command" ecore:transient="true" name="Command" type="xsd:anyURI"/>
   </xsd:complexType>
</xsd:schema>

=== VijayEluri/tuscany-sca-1.x/das/samples/companyweb/src/main/resources/CompanyConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xsi:noNamespaceSchemaLocation="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
    <Command name="all companies" SQL="select * from COMPANY" kind="Select"/>
    
    <Command name="all companies and departments" SQL="select * from COMPANY left outer join DEPARTMENT on COMPANY.ID = DEPARTMENT.COMPANYID" kind="Select"/>

    <Command name="all departments for company" SQL="select * from COMPANY inner join DEPARTMENT on COMPANY.ID = DEPARTMENT.COMPANYID where COMPANY.ID = :ID" kind="Select"/>

    <Command name="company by id with departments" SQL="select * from COMPANY left outer join DEPARTMENT on COMPANY.ID = DEPARTMENT.COMPANYID where COMPANY.ID = :ID" kind="Select"/>
	

	   <ConnectionProperties dataSource="java:comp/env/jdbc/dastest"/>
 

<!--
    <ConnectionProperties driverClassName="org.apache.derby.jdbc.EmbeddedDriver"
        driverURL="jdbc:derby:dastest"/>
--> 
    <Table name="COMPANY">
        <Column name="ID" primaryKey="true" generated="true"/>
    </Table>
    
	<Table name="DEPARTMENT">
		<Column name="ID" primaryKey="true" generated="true"/>
	</Table>
	
	<Relationship name="departments" primaryKeyTable="COMPANY" foreignKeyTable="DEPARTMENT" many="true">
      <KeyPair primaryKeyColumn="ID" foreignKeyColumn="COMPANYID"/>
    </Relationship>
	
	
</Config>

=== VijayEluri/tuscany-sca-1.x/das/rdb/src/test/resources/1xM_mapping_no_cud.xml
<?xml version="1.0" encoding="ASCII"?>
<Config xsi:noNamespaceSchemaLocation="../../main/resources/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <Table name="CUSTOMER" propertyName="Customer">
    <Column name="ID" propertyName="iD" primaryKey="true"/>
  </Table>
  
  <Table name="ANORDER" propertyName="AnOrder">
  	<Column name="CUSTOMER_ID" propertyName="customerID"/>
    <Column name="ID" propertyName="iD" primaryKey="true"/>
  </Table>
	
  <Relationship name="orders" primaryKeyTable="CUSTOMER" foreignKeyTable="ANORDER" many="true">
     <KeyPair primaryKeyColumn="ID" foreignKeyColumn="CUSTOMER_ID"/>
  </Relationship>
  
</Config>
