=== VijayEluri/tuscany-sca-1.x/das/rdb/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:org.apache.tuscany.das.rdb.config="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" ecore:nsPrefix="org.apache.tuscany.das.rdb.config" ecore:package="org.apache.tuscany.das.rdb.config" targetNamespace="http:///org.apache.tuscany.das.rdb/config.xsd">
   <xsd:import namespace="http://www.eclipse.org/emf/2002/Ecore" schemaLocation="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.xsd"/>
   <xsd:element ecore:ignore="true" name="Config" type="org.apache.tuscany.das.rdb.config:Config"/>
   <xsd:element ecore:ignore="true" name="Command" type="org.apache.tuscany.das.rdb.config:Command"/>
   <xsd:element ecore:ignore="true" name="ConnectionProperties" type="org.apache.tuscany.das.rdb.config:ConnectionProperties"/>
   <xsd:element ecore:ignore="true" name="Parameter" type="org.apache.tuscany.das.rdb.config:Parameter"/>
   <xsd:element ecore:ignore="true" name="Relationship" type="org.apache.tuscany.das.rdb.config:Relationship"/>
   <xsd:element ecore:ignore="true" name="Table" type="org.apache.tuscany.das.rdb.config:Table"/>
   <xsd:element ecore:ignore="true" name="KeyPair" type="org.apache.tuscany.das.rdb.config:KeyPair"/>
   <xsd:element ecore:ignore="true" name="Column" type="org.apache.tuscany.das.rdb.config:Column"/>
   <xsd:element ecore:ignore="true" name="ResultDescriptor" type="org.apache.tuscany.das.rdb.config:ResultDescriptor"/>
   <xsd:complexType name="Config">
      <xsd:sequence>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Command" type="org.apache.tuscany.das.rdb.config:Command"/>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" minOccurs="0" name="ConnectionProperties" type="org.apache.tuscany.das.rdb.config:ConnectionProperties"/>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Table" type="org.apache.tuscany.das.rdb.config:Table"/>
         <xsd:element ecore:opposite="Config" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Relationship" type="org.apache.tuscany.das.rdb.config:Relationship"/>
      </xsd:sequence>
      <xsd:attribute name="uri" type="xsd:string"/>
   </xsd:complexType>
   <xsd:complexType name="Command">
      <xsd:sequence>
         <xsd:element ecore:opposite="Command" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Parameter" type="org.apache.tuscany.das.rdb.config:Parameter"/>
         <xsd:element ecore:opposite="Command" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="ResultDescriptor" type="org.apache.tuscany.das.rdb.config:ResultDescriptor"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="SQL" type="xsd:string"/>
      <xsd:attribute name="kind" type="xsd:string"/>
      <xsd:attribute ecore:opposite="Command" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="ConnectionProperties">
      <xsd:attribute name="dataSource" type="xsd:string"/>
      <xsd:attribute name="driverClassName" type="xsd:string"/>
      <xsd:attribute name="driverURL" type="xsd:string"/>
      <xsd:attribute name="driverPassword" type="xsd:string"/>
      <xsd:attribute name="driverUserName" type="xsd:string"/>
      <xsd:attribute ecore:opposite="ConnectionProperties" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Parameter">
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="columnType" type="xsd:string"/>
      <xsd:attribute ecore:opposite="Parameter" ecore:reference="org.apache.tuscany.das.rdb.config:Command" ecore:transient="true" name="Command" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Relationship">
      <xsd:sequence>
         <xsd:element ecore:opposite="Relationship" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="KeyPair" type="org.apache.tuscany.das.rdb.config:KeyPair"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="primaryKeyTable" type="xsd:string"/>
      <xsd:attribute name="foreignKeyTable" type="xsd:string"/>
      <xsd:attribute name="many" type="xsd:boolean"/>
      <xsd:attribute ecore:opposite="Relationship" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Table">
      <xsd:sequence>
         <xsd:element ecore:opposite="Table" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="Column" type="org.apache.tuscany.das.rdb.config:Column"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="propertyName" type="xsd:string"/>
      <xsd:attribute name="create" type="xsd:string"/>
      <xsd:attribute name="update" type="xsd:string"/>
      <xsd:attribute name="delete" type="xsd:string"/>
      <xsd:attribute ecore:opposite="Table" ecore:reference="org.apache.tuscany.das.rdb.config:Config" ecore:transient="true" name="Config" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="KeyPair">
      <xsd:attribute name="primaryKeyColumn" type="xsd:string"/>
      <xsd:attribute name="foreignKeyColumn" type="xsd:string"/>
      <xsd:attribute ecore:opposite="KeyPair" ecore:reference="org.apache.tuscany.das.rdb.config:Relationship" ecore:transient="true" name="Relationship" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="Column">
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="propertyName" type="xsd:string"/>
      <xsd:attribute name="converterClassName" type="xsd:string"/>
      <xsd:attribute name="columnType" type="xsd:string"/>
      <xsd:attribute name="primaryKey" type="xsd:boolean"/>
      <xsd:attribute name="generated" type="xsd:boolean"/>
      <xsd:attribute name="collision" type="xsd:boolean"/>
      <xsd:attribute ecore:opposite="Column" ecore:reference="org.apache.tuscany.das.rdb.config:Table" ecore:transient="true" name="Table" type="xsd:anyURI"/>
   </xsd:complexType>
   <xsd:complexType name="ResultDescriptor">
      <xsd:attribute name="columnName" type="xsd:string"/>
      <xsd:attribute name="tableName" type="xsd:string"/>
      <xsd:attribute name="columnType" type="xsd:string"/>
      <xsd:attribute name="converter" type="xsd:string"/>
      <xsd:attribute ecore:opposite="ResultDescriptor" ecore:reference="org.apache.tuscany.das.rdb.config:Command" ecore:transient="true" name="Command" type="xsd:anyURI"/>
   </xsd:complexType>
</xsd:schema>

=== VijayEluri/tuscany-sca-1.x/java/das/rdb/src/test/resources/CompanyEmployeeConfig.xml
<?xml version="1.0" encoding="ASCII"?>
<!--
  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<Config xsi:noNamespaceSchemaLocation="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		
	<Command name="get all companies" SQL="select * from COMPANY" kind = "Select"/>
	
	<Command name="get named employee" SQL="select * from EMPLOYEE where NAME=:NAME" kind = "Select">
  		<Parameter name=":NAME"/>
  	</Command>
  	
	<Command name="get named employee with company" 
		SQL="select * from EMPLOYEE left outer join COMPANY on EMPLOYEE.ID = COMPANY.EOTMID where EMPLOYEE.NAME=:NAME" kind = "Select">
  		<Parameter name=":NAME"/>
  	</Command>

	  	<Command name="get employee by ID" SQL="select * from EMPLOYEE where ID=:PARAM1" kind = "Select">
  		<Parameter name=":PARAM1"/>
  	</Command>
  	
  	<Command name="get all employees" SQL="select * from EMPLOYEE" kind = "Select"/>
  	
    <Command name="get companies with employee of the month" 
		SQL="select * from COMPANY left outer join EMPLOYEE on COMPANY.EOTMID = EMPLOYEE.ID" kind="Select"/>

<!--	  
  	<Command name="get company and employee of the month" 
  		SQL="select C.*, E.* from COMPANY AS C, EMPLOYEE AS E
  		where C.EOTMID = E.ID" kind = "Select">
  		
  	</Command>
	-->
  	
    <ConnectionProperties driverClassName="org.apache.derby.jdbc.EmbeddedDriver"
        driverURL="jdbc:derby:dastest"/>

	<Table name="COMPANY">
    	<Column name="ID" primaryKey="true" generated="true"/>
  	</Table>
  
  	<Table name="DEPARTMENT">
   		<Column name="ID" primaryKey="true" generated="true"/>
  	</Table>
  		
  	<Table name="EMPLOYEE">
  	  	<Column name="ID" primaryKey="true" generated="true"/>
  	</Table>	
	  	
	<Relationship name="company->employee" primaryKeyTable="EMPLOYEE" foreignKeyTable="COMPANY" many="false" >
      	<KeyPair primaryKeyColumn="ID" foreignKeyColumn="EOTMID" />
  	</Relationship>
			
</Config>

=== VijayEluri/tuscany-sca-1.x/das/rdb/src/test/resources/companyMappingWithConverters.xml
<?xml version="1.0" encoding="ASCII"?>
<Config xsi:noNamespaceSchemaLocation="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <Table name="COMPANY" propertyName="CompanyType">
    <Column name="ID" primaryKey="true"/>
  </Table>
  
  <Table name="DEPARTMENT" propertyName="DepartmentType">
    <Column name="ID" primaryKey="true"/>
    <Column name="NUMBER" converterClassName="org.apache.tuscany.das.rdb.test.mappings.StringToIntegerConverter"/>
  </Table>

  <Table name="EMPLOYEE" propertyName="EmployeeType">
  	  <Column name="ID" primaryKey="true"/>
  	  <Column name="MANAGER" converterClassName="org.apache.tuscany.das.rdb.test.mappings.IntegerToBooleanConverter"/>
  </Table>	
	
  <Relationship name="departments" primaryKeyTable="COMPANY" foreignKeyTable="DEPARTMENT" many="true">
     <KeyPair primaryKeyColumn="ID" foreignKeyColumn="COMPANYID"/>
  </Relationship>	

  <Relationship name="employees" primaryKeyTable="DEPARTMENT" foreignKeyTable="EMPLOYEE" many="true">
     <KeyPair primaryKeyColumn="ID" foreignKeyColumn="DEPARTMENTID"/>
  </Relationship>	
	
</Config>

=== VijayEluri/tuscany-sca-1.x/das/rdb/src/test/resources/companyMapping.xml
<?xml version="1.0" encoding="ASCII"?>
<Config xsi:noNamespaceSchemaLocation="../../main/resources/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <Table name="COMPANY" propertyName="CompanyType">
    <Column name="ID" primaryKey="true"/>
  </Table>
  
  <Table name="DEPARTMENT" propertyName="DepartmentType">
    <Column name="ID" primaryKey="true"/>
  </Table>
  <Table name="EMPLOYEE" propertyName="EmployeeType">
  	  <Column name="ID" primaryKey="true"/>
  </Table>
  
  <Relationship name="departments" primaryKeyTable="COMPANY" foreignKeyTable="DEPARTMENT" many="true">
     <KeyPair primaryKeyColumn="ID" foreignKeyColumn="COMPANYID"/>
  </Relationship>	

  <Relationship name="employees" primaryKeyTable="DEPARTMENT" foreignKeyTable="EMPLOYEE" many="true">
     <KeyPair primaryKeyColumn="ID" foreignKeyColumn="DEPARTMENTID"/>
  </Relationship>	
	
</Config>

=== VijayEluri/tuscany-sca-1.x/das/rdb/src/test/resources/CompanyEmployeeConfig.xml
<?xml version="1.0" encoding="ASCII"?>
<!--
  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<Config xsi:noNamespaceSchemaLocation="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		
	<Command name="get all companies" SQL="select * from COMPANY" kind = "Select"/>
	
	<Command name="get named employee" SQL="select * from EMPLOYEE where NAME= ?" kind = "Select"/>
  	
	<Command name="get named employee with company" 
		SQL="select * from EMPLOYEE left outer join COMPANY on EMPLOYEE.ID = COMPANY.EOTMID where EMPLOYEE.NAME= ?" kind = "Select"/>

	<Command name="get employee by ID" SQL="select * from EMPLOYEE where ID= ?" kind = "Select"/>
  	
  	<Command name="get all employees" SQL="select * from EMPLOYEE" kind = "Select"/>
  	
    <Command name="get companies with employee of the month" 
		SQL="select * from COMPANY left outer join EMPLOYEE on COMPANY.EOTMID = EMPLOYEE.ID" kind="Select"/>


	<Table tableName="COMPANY">
    	<Column columnName="ID" primaryKey="true" generated="true"/>
  	</Table>
  
  	<Table tableName="DEPARTMENT">
   		<Column columnName="ID" primaryKey="true" generated="true"/>
  	</Table>
  		
  	<Table tableName="EMPLOYEE">
  	  	<Column columnName="ID" primaryKey="true" generated="true"/>
  	</Table>	
	  	
	<Relationship name="company->employee" primaryKeyTable="EMPLOYEE" foreignKeyTable="COMPANY" many="false" >
      	<KeyPair primaryKeyColumn="ID" foreignKeyColumn="EOTMID" />
  	</Relationship>
			
</Config>

=== VijayEluri/tuscany-sca-1.x/das/rdb/src/test/resources/PartsConfig.xml
<?xml version="1.0" encoding="ASCII"?>
<!--
  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<Config xsi:noNamespaceSchemaLocation="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  	
  <Command name="readEngineParts" kind="Select" SQL="SELECT P1.*, P2.*, P3.* FROM PART AS P1 
  				LEFT JOIN PART AS P2 ON P1.ID = P2.PARENT_ID 
  					LEFT JOIN PART AS P3 on P2.ID = P3.PARENT_ID WHERE P1.ID = 1">
  					<ResultDescriptor columnName="ID" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					<ResultDescriptor columnName="NAME" columnType="commonj.sdo.String" tableName="PART"/>
  					<ResultDescriptor columnName="QUANTITY" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					<ResultDescriptor columnName="PARENT_ID" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					
  					<ResultDescriptor columnName="ID" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					<ResultDescriptor columnName="NAME" columnType="commonj.sdo.String" tableName="PART"/>
  					<ResultDescriptor columnName="QUANTITY" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					<ResultDescriptor columnName="PARENT_ID" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					
  					<ResultDescriptor columnName="ID" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					<ResultDescriptor columnName="NAME" columnType="commonj.sdo.String" tableName="PART"/>
  					<ResultDescriptor columnName="QUANTITY" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					<ResultDescriptor columnName="PARENT_ID" columnType="commonj.sdo.IntObject" tableName="PART"/>
  					
  </Command>
  
  <Table tableName="PART">
  	<Column columnName="ID" primaryKey="true"/>
  </Table>
  
  <Relationship name="subparts" primaryKeyTable="PART" foreignKeyTable="PART" many="true">
     <KeyPair primaryKeyColumn="ID" foreignKeyColumn="PARENT_ID"/>
  </Relationship>	
	
</Config>

=== VijayEluri/tuscany-sca-1.x/samples/bigbank/account/src/main/resources/DasAccountConfiguration.xml
<?xml version="1.0" encoding="ASCII"?>
<Config xsi:noNamespaceSchemaLocation="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <Table name="CUSTOMERS" propertyName="CustomerProfileData">
    <!-- Column name="firstName" primaryKey="true"/ -->
    <Column name="FIRSTNAME"/>
    <Column name="LASTNAME"/> 
    <Column name="ADDRESS"/> 
    <Column name="EMAIL"/>
     <Column name="LOGINID"/> 
     <Column name="PASSWORD"/> 
      <Column name="ID"/> 
  </Table>
  <Table name="ACCOUNTS" propertyName="AccountSummary">
    <!-- Column name="firstName" primaryKey="true"/ -->
    <Column name="ACCOUNTNUMBER"/>
    <Column name="BALANCE"/> 
  </Table>

<!--
"create table stocks(id int NOT NULL, Symbol varchar(8) NOT NULL, quantity int NOT NULL, purchasePrice real NOT NULL, purchaseDate TIMESTAMP, purchaseLotNumber int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY  )");
-->	
  <Table name="STOCKS" propertyName="StockSummary" >
    
    <Column name="ID"/>
    <Column name="Symbol"/>
    <Column name="quantity"/>
    <Column name="purchasePrice"/>
    <Column name="PURCHASEDATE" converterClassName="org.apache.tuscany.samples.bigbank.account.services.accountdata.AccountDataServiceDASImpl$DateConverter"/>
  </Table>

	
  <Command name="update balance"
        SQL="update ACCOUNTS set BALANCE = :BALANCE where ACCOUNTNUMBER = :ACCOUNTNUMBER"
        kind="Update">
        <Parameter name=":BALANCE"/>
        <Parameter name=":ACCOUNTNUMBER"/>
    </Command>
    
    
    <Command name="all stocks" SQL="select * from stocks"  kind="Select"/>
    <Command name="all customers" SQL="select * from CUSTOMERS"  kind="Select"/>
    
	
</Config>

=== VijayEluri/tuscany-sca-1.x/das/rdb/src/test/resources/BooksConfigWithAlias.xml
<?xml version="1.0" encoding="ASCII"?>
<!--
  Copyright (c) 2005 The Apache Software Foundation or its licensors, as applicable.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<Config xsi:noNamespaceSchemaLocation="http:///org.apache.tuscany.das.rdb/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
     
    <Command name="get all books" SQL="SELECT * FROM BOOK" kind="Select"/>
    
    <Command name="get Cat in the Hat" SQL="SELECT * FROM BOOK WHERE NAME = 'Cat in the Hat'" kind="Select"/>
    
    <Command name="get book by ID" SQL="SELECT * FROM BOOK WHERE BOOK.BOOK_ID = ?" kind="Select"/>
    
    
    
    <Table tableName="BOOK" typeName="Book">
        <Column columnName="BOOK_ID" primaryKey="true"/>
        <Column columnName="AUTHOR" propertyName="Writer"/>
	    <Column columnName="OCC" collision="true"/>
    </Table>
    
</Config>

=== VijayEluri/tuscany-sca-1.x/das/rdb/src/test/resources/CustOrdersConnectionProps.xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xsi:noNamespaceSchemaLocation="../../main/resources/config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
    <Command name="all customers" SQL="select * from CUSTOMER" kind="Select"/>
    
    <Command name="customer and orders"
        SQL="select * from CUSTOMER left join ANORDER on CUSTOMER.ID = ANORDER.CUSTOMER_ID where CUSTOMER.ID = :ID"
        kind="Select">
        <Parameter name=":ID"/>
    </Command>
    
    <Command name="customer and orders"
        SQL="select * from CUSTOMER left join ANORDER on CUSTOMER.ID = ANORDER.CUSTOMER_ID where CUSTOMER.ID = :ID"
        kind="Select">
        <Parameter name=":ID"/>
    </Command>
    
    <!-- Test usage of '?' rather than named parameter -->
    <Command name="order by id with ?" SQL="select * from ANORDER where ANORDER.ID = ?"
        kind="Select">
        <Parameter name=":ID"/>
    </Command>
    
    <Command name="update customer"
        SQL="update CUSTOMER set LASTNAME = 'Pavick' where ID = :ID"
        kind="Update">
        <Parameter name=":ID"/>
    </Command>
    
    <ConnectionProperties driverClassName="org.apache.derby.jdbc.EmbeddedDriver"
        driverURL="jdbc:derby:dastest"/>
    
    <Table name="CUSTOMER">
        <Column name="ID" primaryKey="true"/>
    </Table>
    
    <Table name="ANORDER">
        <Column name="ID" primaryKey="true"/>
    </Table>
    
    <Relationship name="orders" primaryKeyTable="CUSTOMER"
        foreignKeyTable="ANORDER" many="true">
        <KeyPair primaryKeyColumn="ID" foreignKeyColumn="CUSTOMER_ID"/>
    </Relationship>
    
</Config>
